export const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS'
export const GET_ALL_ITEMS_FAILURE = 'GET_ALL_ITEMS_FAILURE'
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const GET_ALL_OPTIONS = 'GET_ALL_OPTIONS';